Repository Hyp-ed/hyped-2021, pull requests merged in 2021-01, with the labels that each got.

#21 QA kalman test
  test/src/Test.files
  test/src/utils/kalman_multivariate.test.cpp
Labels: Testing, enhancement, quality-assurance

#19 New state machine implementation
  src/data/data.hpp
  src/state_machine/event.hpp
  src/state_machine/hyped-machine.cpp
  src/state_machine/hyped-machine.hpp
  src/state_machine/main.cpp
  src/state_machine/main.hpp
  src/state_machine/state.cpp
  src/state_machine/state.hpp
  src/state_machine/states.cpp
  src/state_machine/states.hpp
  src/state_machine/transitions.cpp
  src/state_machine/transitions.hpp
  src/telemetry/recvloop.cpp
  test/src/state_machine/dummy.test.cpp
Labels: enhancement, quality-assurance, state-machine

#35 Implemented deconstructors to avoid memory leaks in embrakes
  src/embrakes/fake_stepper.hpp
  src/embrakes/interface.hpp
  src/embrakes/main.cpp
  src/embrakes/main.hpp
  src/embrakes/stepper.hpp
Labels: enhancement, sensors
